package org.commontech.gardentown.domain.finance;

public enum SubAccountType {
    MEMBERSHIP, GARDEN, ELECTRICITY_USAGE, ELECTRICITY_LOSS, WATER_USAGE, WATER_LOSS, WATER_LUMP_SUM, TRASH, INVESTMENT_MULTIYEAR, ENTRY, INVESTMENT_FOR_NEW_RENTERS, INTEREST, POSTSTAMPS, ELECTRICITY_INSTALLATION, LEGAL, OTHER
}
